spring:
  datasource:
    url: jdbc:mysql://database-1.cgqeftarzgcu.us-east-2.rds.amazonaws.com:3306/tiny_twitter
    username: admin
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
